# Generated by Django 4.2.3 on 2023-07-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExercisePlan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCreation', models.DateTimeField(blank=True, null=True)),
                ('Session_Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_plan', to='ExercisePlan.exercise_plan')),
            ],
        ),
    ]
