# Generated by Django 4.2.3 on 2023-07-28 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Physiotherapist', '0001_initial'),
        ('Patient', '0001_initial'),
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfStart', models.DateField()),
                ('DateOfEnd', models.DateField()),
                ('RepitionNum', models.PositiveIntegerField()),
                ('LinkSide', models.CharField(max_length=50)),
                ('Angle', models.FloatField()),
                ('Difficulty', models.CharField(max_length=50)),
                ('Notes', models.CharField(max_length=500)),
                ('RestTime', models.PositiveIntegerField()),
                ('Game_Exerplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game_Plan', to='Game.game')),
                ('Patient_Exerplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_Plan', to='Patient.patient')),
                ('Physio_Exerplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Physio_Plan', to='Physiotherapist.physiotherapist')),
            ],
        ),
    ]
