# Generated by Django 4.2.3 on 2023-07-27 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Physiotherapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='patient_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Physio_Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Physiotherapist.physiotherapist')),
            ],
        ),
    ]
